### PR TITLE
Feature/8 fee tests

### PR DESCRIPTION
**Pull request by cryptomental**
Hi @pelsasser , I cleaned-up test code, added beforeEach, extracted common parts and created seven test cases. All non-zero fees test cases fail: maker fee, taker fee, maker & taker fee. This needs to be investigated further, could you please have a look?

### CODE REVIEW

**Comment by cryptomental** [comment]
OrderFilled() event is not transmitted and I suspect the bad thing happens here https://github.com/MarketProject/MarketProtocol/blob/master/contracts/MarketContract.sol#L201 and here https://github.com/MarketProject/MarketProtocol/blob/master/contracts/MarketContract.sol#L210

**Comment by pelsasser** [comment]
@cryptomental - I looked through this quite a bit.
 
Took me forever but I am pretty sure there are a few issues

- the fees that are being paid are in MKT tokens, they are not transfered into the collateral pool, but rather allocated to the address of the `feeRecipient`
- Additionally, the party paying the fees (maker or taker) must call `approve` to allow the transfer of the MKT tokens from their address to the address of the feeRecipient

I think I should be able to get this fixed and will push a commit once done

**Comment by pelsasser** [comment]
https://github.com/MarketProject/MarketProtocol/tree/cryptomental-feature/8-fee-tests

getting closer...

**Comment by cryptomental** [comment]
Fingers crossed...

**Comment by pelsasser** [comment]
I think I found the other issue - the taker address has no MKT tokens :)  
should be resolved shortly

**Comment by pelsasser** [comment]
okay take a look at that branch - all tests are passing

**Comment by cryptomental** [comment]
Good job! https://travis-ci.org/MarketProject/MarketProtocol/builds/332014121
That was a tricky one to figure out. I am missing a step-by-step solidity debugger integrated to intellij...

**Comment by pelsasser** [comment]
I wish that existed.  I used events to act as a debugger in solidity to see what lines where failing. PITA for sure.

**Comment by pelsasser** [comment]
closing and will create new PR with cryptomental-feature/8-fee-tests branch

**Pull request closed without merging**
