### PR TITLE
.travis.yml: Pass CONTINUOUS_INTEGRATION variable to coverage.

### PR DESCRIPTION
**Pull request by cryptomental**
The variable enables coveralls.

Issue: #21

### CODE REVIEW

**Comment by cryptomental** [comment]
It fails with

```
/app/node_modules/coveralls/bin/coveralls.js:18
        throw err;
        ^
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}
The command "docker-compose exec truffle-coverage env CONTINUOUS_INTEGRATION=true scripts/coverage_run.sh" exited with 1.
```

I believe this is coveralls set up related, but the variable is correctly consumed.

**Comment by cryptomental** [comment]
@pelsasser have a look here: https://coveralls.io/builds/14944695 :-)

I executed the branch locally and set .coveralls.yml to push result to coveralls.io. I am wondering why automatic pushes from GitHub do not work, but I hope that this will help you to proceed.

**Comment by perfectmak** [comment]
Everything seems to be okay now according to the build of this PR #23.
I fixed that failing test during coverage and everything should be fine.

**Comment by cryptomental** [comment]
Hi @perfectmak cool, I also fixed the coveralls here https://github.com/MarketProject/MarketProtocol/pull/24

**Pull request closed without merging**
