### PR TITLE
modifying test token to allow for more flexibility while create dApp

### PR DESCRIPTION
**Pull request by pelsasser**

### CODE REVIEW

**Comment by pelsasser** [comment]
@perfectmak @cryptomental can you guys take a look at the failing Travis tests here.   Happy to tip of fixing the issue.  Looks like its a mismatch in compiler version vs our solidity code base.

**Comment by cryptomental** [comment]
@pelsasser I will have a look.

**Comment by pelsasser** [comment]
@cryptomental still failing - which seems odd

**Comment by cryptomental** [comment]
@pelsasser this pull request just needs to be rebased to current master branch, then it will be fine. 
I cannot fix this branch as I do not have write permissions but I will rebase my fork and open a PR to this branch to fix it.

**Pull request merged**
