### PR TITLE
Fix docker compose volume error

### PR DESCRIPTION
**Pull request by perfectmak**
Change Volumes from Named volumes to bind volume types.

### CODE REVIEW

**Comment by cryptomental** [comment]
Hmm that's interesting, @perfectmak what kind of volume error did you have?

**Comment by perfectmak** [comment]
@cryptomental error message was:
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.truffle-coverage.volumes contains unsupported option: 'name'
services.truffle.volumes contains unsupported option: 'name'
```

It appears to start if you are using the latest version `1.18.0` of docker-compose.
But ideally, I believe this is also what you wanted to achieve right?

**Comment by cryptomental** [comment]
The named volumes syntax is supported since Docker Engine 17.09 release, this matches docker-compose 3.4 syntax, see https://docs.docker.com/compose/compose-file/compose-versioning/#version-34

My currently installed is docker-compose version 1.17.0, build ac53b73

**Comment by cryptomental** [comment]
You are right this happens after upgrade to 1.18.0.

$ docker-compose --version
docker-compose version 1.18.0, build 8dd22a9

$ docker-compose up
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.truffle-coverage.volumes contains unsupported option: 'name'
services.truffle.volumes contains unsupported option: 'name'

Release notes do not mention anything https://github.com/docker/compose/releases/tag/1.18.0

**Pull request merged**
