### PR TITLE
Feature/test oraclize gas within limit

### PR DESCRIPTION
**Pull request by cryptomental**
Solves #50 .

### CODE REVIEW

**Comment by cryptomental** [comment]
And the coverage increased +4% :)

**Comment by cryptomental** [comment]
If needed, I can squash commits into one and remove the commented out logs.

**Comment by pelsasser** [comment]
tested this with truffle and ganache and both worked.  Will attempt a test net in the future, but that can be pushed down the line a bit.  Thanks, this is awesome!

**Comment by cryptomental** [comment]
@pelsasser great! I tried to 'submit work'  on gitcoin but it failed https://etherscan.io/tx/0x83efb8c29abfd6d51e93a56e1d23259b38597eca153b7fa726106c326f7e80a6 unfortunately I cannot re-submit it again. I would be grateful if you could have a look and see if this can be closed.

**Comment by pelsasser** [comment]
@cryptomental - please should me a message with your ETH address and I can get everything squared out.  Thanks again

**Pull request merged**
