### PR TITLE
bring test coverage for MarketCollateralPool.sol to 100% issue #28

### PR DESCRIPTION
**Pull request by craig-iam-smith**
Just some requires and a 'if' showing as branch not covered

### CODE REVIEW

**Comment by cryptomental** [comment]
Ok, great, from the branch coverage just a few cases are missing: calling settleAndClose when contract is not settled, checks for isUserEnabledForContract and calling settleAndClose() when user net position is 0. Can the last one happen at all or should be changed to an assert?

**Comment by pelsasser** [comment]
@cryptomental - yes, the last one could happen.  User has flattened their position prior to settlement however has left funds in the contract.  The contract then settles, and settleAndClose() just gives them an easy way of withdrawing all of their balance.

**Comment by craig-iam-smith** [comment]
@pelsasser - I have a test written for that case now in my fork.  Branch cases covered except, I have no tests where require(MarketToken.isUserEnabledForContract(...) fails,  I'm looking that now.

**Comment by craig-iam-smith** [comment]
Line coverage 100%, Branch coverage is as good as can be, both requires can only be reached from a function that has already executed the same require.

**Comment by pelsasser** [comment]
@craig-iam-smith - thanks!

I thought about removing those require statements since for now they are, as you stated, redundant.  My concern is that at some point in the future they may be called in a different fashion.  

We could always comment them out and leave a note so at least its documented....thoughts?

**Comment by craig-iam-smith** [comment]
I would comment out them out and leave a note.  Any future callers should call the same require and a note left may prevent a future issue.

**Pull request merged**
